const leagues = ['Premier League','LaLiga EA Sports','Serie A','Bundesliga','Ligue 1','Brasileirão Série A','Liga Portugal','Eredivisie','Championship','MLS','Liga MX','Superliga Argentina','Jupiler Pro League','Süper Lig','Saudi Pro League','J1 League','Scottish Premiership'];
const icons = ['🏴','🇪🇸','🇮🇹','🇩🇪','🇫🇷','🇧🇷','🇵🇹','🇳🇱','🏴','🇺🇸','🇲🇽','🇦🇷','🇧🇪','🇹🇷','🇸🇦','🇯🇵','🏴'];
const plays = [
 ['Pressão alta!', 'Cunha aperta a saída de bola e recupera no campo de ataque.'],['Bola na trave!', 'Neto recebe na entrada da área e acerta o poste. Quase o primeiro!'],['Defesa espetacular!', 'João Pedro bate colocado, mas Sá voa para espalmar.'],['Cruzamento perigoso', 'Aït-Nouri ganha na ponta e manda na área. A defesa afasta de cabeça.'],['Contra-ataque veloz', 'Brighton acelera em três toques, procurando espaço entre os zagueiros.'],['Que chance!', 'Sarabia invade a área e finaliza por cima do gol.'],['Chute bloqueado', 'A finalização de fora da área explode na marcação.'],['Cabeceio no canto', 'O cruzamento encontra a cabeça do atacante, mas passa raspando a trave.'],['Falta na entrada', 'Boa chance em bola parada para os Wolves.'],['Saída de goleiro', 'O goleiro lê o lançamento e chega antes do centroavante.'],['Tabela envolvente', 'Dois passes rápidos desmontam a linha de marcação.'],['Drible pela direita', 'O ponta corta para dentro e deixa o marcador para trás.'],['Escanteio fechado', 'A bola atravessa a pequena área e ninguém consegue completar.'],['Finalização de primeira', 'O atacante pega de voleio, mas a bola sobe demais.'],['Lançamento preciso', 'Uma inversão longa encontra o lateral com muito campo à frente.'],['Carrinho salvador', 'O defensor se joga no momento exato e evita o arremate.'],['Bola enfiada', 'O meia acha um corredor e coloca o companheiro cara a cara.'],['Corte providencial', 'A zaga intercepta o cruzamento quando ele parecia certo para gol.'],['Chute de longe', 'Uma bomba de fora da área obriga o goleiro a trabalhar.'],['Jogada trabalhada', 'Os donos da casa trocam passes com paciência no terço final.'],['Arrancada individual', 'O atacante ganha na velocidade e invade a grande área.'],['Defesa dupla!', 'O goleiro segura o primeiro chute e ainda reage ao rebote.'],['Passe de calcanhar', 'Um toque de classe abre espaço na intermediária.'],['Bola parada ensaiada', 'A cobrança curta surpreende, mas a finalização sai sem direção.'],['Disputa aérea', 'Os zagueiros vencem a batalha pelo alto na área.'],['Ataque pela esquerda', 'O corredor fica livre e o time avança com perigo.'],['Quase contra', 'O desvio na área muda a trajetória e assusta o goleiro.'],['Meia-lua', 'O camisa 10 gira sob pressão e procura o chute colocado.'],['Linha de impedimento', 'A defesa sobe junta e flagra o atacante adiantado.'],['Pressão final', 'A torcida aumenta o volume e o time empurra pelo gol.'],['Triangulação perfeita', 'A troca de passes deixa o atacante livre para decidir.']];
const players = document.querySelector('#players'), ball = document.querySelector('#ball');
const coords = [[8,50],[18,25],[19,75],[30,45],[34,65],[39,31],[44,51],[48,75],[55,40],[60,60],[66,30],[70,76],[79,48],[85,25],[86,72],[92,50],[14,44],[22,58],[28,34],[36,52],[43,70],[53,28]];
let active=0, clockSeconds=34*60+18, secondHalf=false, total=8, timer;
function renderLeagues(){document.querySelector('#leagueList').innerHTML=leagues.map((l,i)=>`<button class="league ${i===0?'active':''}"><span class="league-icon">${icons[i]}</span>${l}</button>`).join('');document.querySelectorAll('.league').forEach((b,i)=>b.onclick=()=>{document.querySelectorAll('.league').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('.crumb span').textContent=leagues[i]})}
function makePlayers(){players.innerHTML=coords.map((c,i)=>`<div class="player ${(i<11?'home':'away')} ${i===0||i===15?'keeper':''}" style="left:${c[0]}%;top:${c[1]}%">${i<11?i+1:i-10}</div>`).join('');}
function progress(){document.querySelector('#progress').innerHTML=Array.from({length:total},(_,i)=>`<i class="${i<active?'done':i===active?'current':''}"></i>`).join('');document.querySelector('#period').textContent=`${secondHalf?'2º':'1º'} TEMPO · ${Math.min(active+1,secondHalf?total-4:4)}/${secondHalf?total-4:4}`}
function updatePositions(){document.querySelectorAll('.player').forEach((p,i)=>{const base=coords[i];const drift=(Math.random()-.5)*13;p.style.left=Math.max(4,Math.min(92,base[0]+drift))+'%';p.style.top=Math.max(8,Math.min(84,base[1]+(Math.random()-.5)*18))+'%'});ball.style.left=(25+Math.random()*55)+'%';ball.style.top=(20+Math.random()*58)+'%'}
function showMoment(){if(active>=total)return;if(active===4&&!secondHalf){secondHalf=true;clockSeconds=46*60+5;document.querySelector('#momentTitle').textContent='Começa o segundo tempo!';document.querySelector('#commentary').textContent='As equipes voltam para os últimos 45 minutos.';total=8+(Math.random()>.5?1:0)}const play=plays[Math.floor(Math.random()*plays.length)];document.querySelector('#momentTitle').textContent=play[0];document.querySelector('#commentary').textContent=play[1];document.querySelector('#nextMoment').textContent=plays[(active+7)%plays.length][0];document.querySelector('#eventBadge').classList.add('show');setTimeout(()=>document.querySelector('#eventBadge').classList.remove('show'),1200);updatePositions();progress();active++;const h=active%3===0?Math.floor(active/3):Math.ceil(active/3), a=active%4===0?1:Math.floor(active/5);document.querySelector('#shots').innerHTML=`${h+2} <i></i> ${a+2}`;document.querySelector('#chances').innerHTML=`${Math.max(1,h)} <i></i> ${Math.max(1,a)}`;if(active>=total){clearInterval(timer);clearInterval(momentTimer);document.querySelector('#momentTitle').textContent='Fim de jogo';document.querySelector('#commentary').textContent='Uma partida intensa, decidida nos detalhes. Nova simulação disponível.';document.querySelector('#period').textContent='ENCERRADO';}}
function tick(){clockSeconds+=7;const min=Math.floor(clockSeconds/60),sec=clockSeconds%60;document.querySelector('#clock').textContent=`${String(min).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
renderLeagues();makePlayers();progress();ball.style.left='53%';ball.style.top='54%';timer=setInterval(tick,1000);let momentTimer=setInterval(showMoment,6500);document.querySelector('#skipButton').onclick=showMoment;document.querySelector('#newMatch').onclick=()=>location.reload();
